server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:

            
            - id: employee-service
              uri: http://localhost:8082
              predicates:
                - Path=/employees/**,/v3/api-docs/employee

            
            - id: attendance-service
              uri: http://localhost:8083
              predicates:
                - Path=/attendance/**,/v3/api-docs/attendance



springdoc:
  swagger-ui:
    urls:
      - name: Employee Service
        url: /v3/api-docs/employee
      - name: Attendance Service
        url: /v3/api-docs/attendance
      - name: Api Gateway
        url: /v3/api-docs
